### ISSUE TITLE
addNode function does not work for Anaglyph node

### ISSUE THREAD

**Issue by pavelvasev** [xeolabs/scenejs#341]
Lets create scene and add an Anaglyph effect node.
And then dynamically add some new nodes to that Anaglyph node. 
It will not work.

E.g
```
content.addNode( { type: "effects/anaglyph" }, function( newContent ) {
  newContent.addNode( ... ); // <-- nodes added here will not have anaglyph effect.
} );
```

It seems the source of problem is that Anaglyph "redirects" the flow of render tree, adding internal "_leaf" node and moving all static nodes there. 

However when we invoke addNode on Anaglyph node, it doesn't transfer new nodes to those "_leaf" node, but keeps them as own children (e.g. siblings of _leaf);

It seems that this behaviour is spreaded across multiple plugins, not Anaglyph only. 

Maybe is it possible to "override" addNode function for these nodes?

**Comment by xeolabs** [comment]
Yeah I know - it's a limitation of those plugins unfortunately, since as you say, they are in charge of attaching the given child nodes to subtrees that they create internally, where the plugins may have some special place within their subtrees to attach them, that only they know about.

Here's a possible workaround (depending on your usage pattern of course), where you can 

```` javascript

// Make a node
var subroot= myScene.createNode();

// Make it the child of your plugin node:
myParentNode.addNode({
    type: "effects/anaglyph",
    nodes: [subroot]
});

// Now you can add/remove nodes to the sub-root:
subRoot.addNode(....);

````

The problem I had with overriding addNode etc for these plugins was that, for completeness and framework symmetry, I'd have to override all the other methods as well..unless I was to use some sort of fancy inheritance/mixins or whatever.

**Comment by xeolabs** [comment]
Actually, perhaps something like a getRoot or getNodes method would be a good idea on these custom nodes..

**Comment by pavelvasev** [comment]
I agree with you with almost all! Probably, there is no need to implement all the methods, only most important. Or, as you suggest, maybe it is possible to derive plugins from some special class. In this class, override all the methods needed. And in those overrides, check if getRoot exist, and if exist - call it's methods. So plugins have to implement only getRoot().... Maybe it will be good.

```
// Make a node
var subroot= myScene.createNode();

// Make it the child of your plugin node:
myParentNode.addNode({
    type: "effects/anaglyph",
    nodes: [subroot]
});

// Now you can add/remove nodes to the sub-root:
subRoot.addNode(....);
```
Oh, good work-around! Much better than "haking"-style like adding to ._leaf property!
