### ISSUE TITLE
Scenejs support Collada file imports?

### ISSUE THREAD

**Issue by krusk** [xeolabs/scenejs#392]
I saw this post, but can't find any documentation in scene.js on how to import and use Collada files. 

https://www.khronos.org/news/permalink/scenejs-now-supports-collada-import

Are Collada files usable by scene.js, and if so, is there any documentation?

Thanks,

K.

**Comment by xeolabs** [comment]
Hi, that was a really early SceneJS version and COLLADA support has since been removed. The rationale was that parsing COLLADA was too heavy (memory+time) to do client-side - better to pre-parse server-side into something more efficient to load. If you feel like coding a [glTF](https://github.com/KhronosGroup/glTF) loader that would be ideal ;)

**Comment by krusk** [comment]
Thanks for the update. What format do you recommend for scene.js? It looks like JSON.

**Comment by xeolabs** [comment]
@krusk glTF import is on the roadmap for SceneJS - I just [wrote that for xeoEngine recently](https://github.com/xeolabs/xeoengine/tree/master/src/importing), so its very easy to copy and adapt that to SceneJS (parsers are in the "gltf" directory, while "model.js" is just a xeoEngine scene node). I probably won't get around to that for a few weeks, but if you're feeling adventurous, should be fairly easy to adapt it.
