### ISSUE TITLE
Decals emissive example page

### ISSUE THREAD

**Issue by MiD-AwE** [xeolabs/scenejs#420]
The decals: emissive example page fails with Firefox 42.0. The console spits out the following.

TypeError: can't access dead object auth.js:49:7
unreachable code after return statement scenejs.js:12103:8
TypeError: can't access dead object auth.js:49:7
NS_ERROR_NOT_AVAILABLE:  scenejs.js:6384:0

I work in UbuntuGnome 15.10 & Firefox 42.0. (Currently unable to test with any other system or browser).

**Comment by tsherif** [comment]
I think it's due to the fact that [the image used for the decal](https://github.com/xeolabs/scenejs/blob/master/examples/decals_emissive.html#L25) doesn't have a `src`. Firefox might be stricter about this than Chrome.

Here's a discussion about the error: http://stackoverflow.com/questions/17049176/ns-error-not-available-component-is-not-available

**Comment by KlausBlass** [comment]
Under Windows 7, Firefox 42.0, also fails for me.
Error shown on console:

NS_ERROR_NOT_AVAILABLE: 
ctx.drawImage(image,

**Comment by xeolabs** [comment]
BTW after discussion with @tsherif we might not even be including the ````decal```` node in the next release, where decalling might be applied using a regular ````texture```` node.

**Comment by xeolabs** [comment]
Fixed in master by commit https://github.com/xeolabs/scenejs/commit/d6cc65f890142660e2aec6b0a9e48e92b4ac2a57
